//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.10 at 05:48:06 PM IST 
//


package com.generator.data.xmlns.gplace.api.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.generator.data.xmlns.gplace.api.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PlaceDetailsResponse_QNAME = new QName("http://xmlns.data.generator.com/gplace/api/v1", "PlaceDetailsResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.generator.data.xmlns.gplace.api.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PlaceDetailsResponse }
     * 
     */
    public PlaceDetailsResponse createPlaceDetailsResponse() {
        return new PlaceDetailsResponse();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Open }
     * 
     */
    public Open createOpen() {
        return new Open();
    }

    /**
     * Create an instance of {@link OpeningHours }
     * 
     */
    public OpeningHours createOpeningHours() {
        return new OpeningHours();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Aspect }
     * 
     */
    public Aspect createAspect() {
        return new Aspect();
    }

    /**
     * Create an instance of {@link Review }
     * 
     */
    public Review createReview() {
        return new Review();
    }

    /**
     * Create an instance of {@link Photo }
     * 
     */
    public Photo createPhoto() {
        return new Photo();
    }

    /**
     * Create an instance of {@link Close }
     * 
     */
    public Close createClose() {
        return new Close();
    }

    /**
     * Create an instance of {@link AddressComponent }
     * 
     */
    public AddressComponent createAddressComponent() {
        return new AddressComponent();
    }

    /**
     * Create an instance of {@link Geometry }
     * 
     */
    public Geometry createGeometry() {
        return new Geometry();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaceDetailsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.data.generator.com/gplace/api/v1", name = "PlaceDetailsResponse")
    public JAXBElement<PlaceDetailsResponse> createPlaceDetailsResponse(PlaceDetailsResponse value) {
        return new JAXBElement<PlaceDetailsResponse>(_PlaceDetailsResponse_QNAME, PlaceDetailsResponse.class, null, value);
    }

}
