SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `rise` ;
CREATE SCHEMA IF NOT EXISTS `rise` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci ;
USE `rise` ;

-- -----------------------------------------------------
-- Table `rise`.`CONTACT_INFORMATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`CONTACT_INFORMATION` ;

CREATE  TABLE IF NOT EXISTS `rise`.`CONTACT_INFORMATION` (
  `CONTACT_INFORMATION_ID` BIGINT NOT NULL ,
  `STREET_ADDRESS` TEXT NOT NULL ,
  `CITY` VARCHAR(255) NOT NULL ,
  `STATE` VARCHAR(255) NOT NULL ,
  `POSTAL_CODE` VARCHAR(255) NOT NULL ,
  `COUNTRY` VARCHAR(255) NOT NULL ,
  `EMAIL` VARCHAR(255) NOT NULL ,
  `ALTERNATIVE_EMAIL` VARCHAR(255) NOT NULL ,
  `PHONE` VARCHAR(255) NOT NULL ,
  `ALTERNATIVE_PHONE` VARCHAR(255) NOT NULL ,
  `WEBSITE` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`CONTACT_INFORMATION_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rise`.`PERSON_NAME`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`PERSON_NAME` ;

CREATE  TABLE IF NOT EXISTS `rise`.`PERSON_NAME` (
  `PERSON_NAME_ID` BIGINT NOT NULL ,
  `TITLE` VARCHAR(255) NOT NULL ,
  `FIRST_NAME` VARCHAR(255) NOT NULL ,
  `MIDDLE_NAME` VARCHAR(255) NULL ,
  `LAST_NAME` VARCHAR(255) NOT NULL ,
  `SUFFIX` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`PERSON_NAME_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rise`.`PASSPORT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`PASSPORT` ;

CREATE  TABLE IF NOT EXISTS `rise`.`PASSPORT` (
  `PASSPORT_ID` BIGINT NOT NULL ,
  `PASSPORT_NUMBER` VARCHAR(255) NOT NULL ,
  `ISSUED_BY` VARCHAR(255) NOT NULL ,
  `ISSUED_PLACE` VARCHAR(255) NOT NULL ,
  `ISSUED_DATE` DATETIME NOT NULL ,
  `EXPIRY_DATE` DATETIME NOT NULL ,
  `EMIGRATION_CHECK_REQUIRED` TINYINT(1) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`PASSPORT_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rise`.`DRIVERS_LICENSE_VEHICLE_TYPE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`DRIVERS_LICENSE_VEHICLE_TYPE` ;

CREATE  TABLE IF NOT EXISTS `rise`.`DRIVERS_LICENSE_VEHICLE_TYPE` (
  `DRIVERS_LICENSE_VEHICLE_TYPE_ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `CODE` VARCHAR(255) NOT NULL ,
  `DESCRIPTION` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`DRIVERS_LICENSE_VEHICLE_TYPE_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rise`.`DRIVERS_LICENSE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`DRIVERS_LICENSE` ;

CREATE  TABLE IF NOT EXISTS `rise`.`DRIVERS_LICENSE` (
  `DRIVERS_LICENSE_ID` BIGINT NOT NULL ,
  `DRIVERS_LICENSE_VEHICLE_TYPE_ID` BIGINT NOT NULL ,
  `DRIVERS_LICENSE_NUMBER` VARCHAR(255) NOT NULL ,
  `ISSUED_BY` VARCHAR(255) NOT NULL ,
  `ISSUED_STATE` VARCHAR(255) NOT NULL ,
  `ISSUED_PLACE` VARCHAR(255) NOT NULL ,
  `ISSUED_DATE` DATETIME NOT NULL ,
  `EXPIRY_DATE` DATETIME NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`DRIVERS_LICENSE_ID`) ,
  CONSTRAINT `fk_DRIVERS_LICENSE_DRIVERS_LICENSE_VEHICLE_TYPE1`
    FOREIGN KEY (`DRIVERS_LICENSE_VEHICLE_TYPE_ID` )
    REFERENCES `rise`.`DRIVERS_LICENSE_VEHICLE_TYPE` (`DRIVERS_LICENSE_VEHICLE_TYPE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DRIVERS_LICENSE_DRIVERS_LICENSE_VEHICLE_TYPE1_idx` ON `rise`.`DRIVERS_LICENSE` (`DRIVERS_LICENSE_VEHICLE_TYPE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`EDUCATION_QUALIFICATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`EDUCATION_QUALIFICATION` ;

CREATE  TABLE IF NOT EXISTS `rise`.`EDUCATION_QUALIFICATION` (
  `EDUCATION_QUALIFICATION_ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `UNIVERSITY` VARCHAR(255) NOT NULL ,
  `YEAR_COMPLETED` YEAR NOT NULL ,
  `MONTH_COMPLETED` INT NOT NULL ,
  `PERCENTAGE` INT NOT NULL ,
  `GPA` FLOAT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`EDUCATION_QUALIFICATION_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rise`.`EMPLOYMENT_EXPERIENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`EMPLOYMENT_EXPERIENCE` ;

CREATE  TABLE IF NOT EXISTS `rise`.`EMPLOYMENT_EXPERIENCE` (
  `EMPLOYMENT_EXPERIENCE_ID` BIGINT NOT NULL ,
  `EMPLOYER_NAME` VARCHAR(255) NOT NULL ,
  `JOB_TITLE` VARCHAR(255) NOT NULL ,
  `FROM_DATE` DATETIME NOT NULL ,
  `TO_DATE` DATETIME NOT NULL ,
  `DESCRIPTION` TEXT NOT NULL ,
  `REASON_FOR_LEAVING` LONGTEXT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`EMPLOYMENT_EXPERIENCE_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rise`.`AWARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`AWARD` ;

CREATE  TABLE IF NOT EXISTS `rise`.`AWARD` (
  `AWARD_ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `ISSUED_BY` VARCHAR(255) NOT NULL ,
  `DATE_ISSUED` DATETIME NOT NULL ,
  `DESCRIPTION` TEXT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`AWARD_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rise`.`PERSON`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`PERSON` ;

CREATE  TABLE IF NOT EXISTS `rise`.`PERSON` (
  `PERSON_ID` BIGINT NOT NULL ,
  `PERSON_NAME_ID` BIGINT NOT NULL ,
  `PASSPORT_ID` BIGINT NOT NULL ,
  `DRIVERS_LICENSE_ID` BIGINT NOT NULL ,
  `DATE_OF_BIRTH` DATETIME NOT NULL ,
  `AGE` INT NULL ,
  `AADHAAR_NUMBER` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  `CONTACT_INFORMATION_ID` BIGINT NOT NULL ,
  PRIMARY KEY (`PERSON_ID`) ,
  CONSTRAINT `fk_PERSON_PASSPORT1`
    FOREIGN KEY (`PASSPORT_ID` )
    REFERENCES `rise`.`PASSPORT` (`PASSPORT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSON_PERSON_NAME1`
    FOREIGN KEY (`PERSON_NAME_ID` )
    REFERENCES `rise`.`PERSON_NAME` (`PERSON_NAME_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSON_DRIVERS_LICENSE1`
    FOREIGN KEY (`DRIVERS_LICENSE_ID` )
    REFERENCES `rise`.`DRIVERS_LICENSE` (`DRIVERS_LICENSE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PERSON_PASSPORT1_idx` ON `rise`.`PERSON` (`PASSPORT_ID` ASC) ;

CREATE INDEX `fk_PERSON_PERSON_NAME1_idx` ON `rise`.`PERSON` (`PERSON_NAME_ID` ASC) ;

CREATE INDEX `fk_PERSON_DRIVERS_LICENSE1_idx` ON `rise`.`PERSON` (`DRIVERS_LICENSE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`PUBLICATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`PUBLICATION` ;

CREATE  TABLE IF NOT EXISTS `rise`.`PUBLICATION` (
  `PUBLICATION_ID` BIGINT NOT NULL ,
  `PERSON_ID` BIGINT NOT NULL ,
  `PUBLISHED_BY` VARCHAR(255) NOT NULL ,
  `PUBLISHED_DATE` DATETIME NOT NULL ,
  `DESCRIPTION` TEXT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`PUBLICATION_ID`) ,
  CONSTRAINT `fk_PUBLICATION_PERSON1`
    FOREIGN KEY (`PERSON_ID` )
    REFERENCES `rise`.`PERSON` (`PERSON_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PUBLICATION_PERSON1_idx` ON `rise`.`PUBLICATION` (`PERSON_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`PERSON_EDUCATION_QUALIFICATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`PERSON_EDUCATION_QUALIFICATION` ;

CREATE  TABLE IF NOT EXISTS `rise`.`PERSON_EDUCATION_QUALIFICATION` (
  `PERSON_EDUCATION_QUALIFICATION_ID` BIGINT NOT NULL ,
  `PERSON_ID` BIGINT NOT NULL ,
  `EDUCATION_QUALIFICATION_ID` BIGINT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`PERSON_EDUCATION_QUALIFICATION_ID`) ,
  CONSTRAINT `fk_PERSON_has_EDUCATION_QUALIFICATION_PERSON1`
    FOREIGN KEY (`PERSON_ID` )
    REFERENCES `rise`.`PERSON` (`PERSON_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSON_has_EDUCATION_QUALIFICATION_EDUCATION_QUALIFICATION1`
    FOREIGN KEY (`EDUCATION_QUALIFICATION_ID` )
    REFERENCES `rise`.`EDUCATION_QUALIFICATION` (`EDUCATION_QUALIFICATION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PERSON_has_EDUCATION_QUALIFICATION_EDUCATION_QUALIFICATI_idx` ON `rise`.`PERSON_EDUCATION_QUALIFICATION` (`EDUCATION_QUALIFICATION_ID` ASC) ;

CREATE INDEX `fk_PERSON_has_EDUCATION_QUALIFICATION_PERSON1_idx` ON `rise`.`PERSON_EDUCATION_QUALIFICATION` (`PERSON_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`ORGANIZATION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`ORGANIZATION` ;

CREATE  TABLE IF NOT EXISTS `rise`.`ORGANIZATION` (
  `ORGANIZATION_ID` BIGINT NOT NULL ,
  `CONTACT_INFORMATION_ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `DATE_INCORPORATED` DATETIME NOT NULL ,
  `TYPE` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`ORGANIZATION_ID`) ,
  CONSTRAINT `fk_ORGANIZATION_ADDRESS1`
    FOREIGN KEY (`CONTACT_INFORMATION_ID` )
    REFERENCES `rise`.`CONTACT_INFORMATION` (`CONTACT_INFORMATION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ORGANIZATION_ADDRESS1_idx` ON `rise`.`ORGANIZATION` (`CONTACT_INFORMATION_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`STATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`STATE` ;

CREATE  TABLE IF NOT EXISTS `rise`.`STATE` (
  `STATE_ID` BIGINT NOT NULL ,
  `CONTACT_INFORMATION_ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `CODE` VARCHAR(255) NOT NULL ,
  `CAPITAL_CITY` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  `STREET_ADDRESS` VARCHAR(255) NOT NULL ,
  PRIMARY KEY (`STATE_ID`) ,
  CONSTRAINT `fk_STATE_ADDRESS1`
    FOREIGN KEY (`CONTACT_INFORMATION_ID` )
    REFERENCES `rise`.`CONTACT_INFORMATION` (`CONTACT_INFORMATION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_STATE_ADDRESS1_idx` ON `rise`.`STATE` (`CONTACT_INFORMATION_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`MINISTRY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`MINISTRY` ;

CREATE  TABLE IF NOT EXISTS `rise`.`MINISTRY` (
  `MINISTRY_ID` BIGINT NOT NULL ,
  `CONTACT_INFORMATION_ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `MINISTER_NAME` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`MINISTRY_ID`) ,
  CONSTRAINT `fk_MINISTRY_ADDRESS1`
    FOREIGN KEY (`CONTACT_INFORMATION_ID` )
    REFERENCES `rise`.`CONTACT_INFORMATION` (`CONTACT_INFORMATION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MINISTRY_ADDRESS1_idx` ON `rise`.`MINISTRY` (`CONTACT_INFORMATION_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`DEPARTMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`DEPARTMENT` ;

CREATE  TABLE IF NOT EXISTS `rise`.`DEPARTMENT` (
  `DEPARTMENT_ID` BIGINT NOT NULL ,
  `CONTACT_INFORMATION_ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `INCHARGE_OFFICER` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`DEPARTMENT_ID`) ,
  CONSTRAINT `fk_DEPARTMENT_ADDRESS1`
    FOREIGN KEY (`CONTACT_INFORMATION_ID` )
    REFERENCES `rise`.`CONTACT_INFORMATION` (`CONTACT_INFORMATION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DEPARTMENT_ADDRESS1_idx` ON `rise`.`DEPARTMENT` (`CONTACT_INFORMATION_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`MINISTRY_DEPARTMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`MINISTRY_DEPARTMENT` ;

CREATE  TABLE IF NOT EXISTS `rise`.`MINISTRY_DEPARTMENT` (
  `MINISTRY_DEPARTMENT_ID` BIGINT NOT NULL ,
  `MINISTRY_ID` BIGINT NOT NULL ,
  `DEPARTMENT_ID` BIGINT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`MINISTRY_DEPARTMENT_ID`) ,
  CONSTRAINT `fk_MINISTRY_has_DEPARTMENT_MINISTRY1`
    FOREIGN KEY (`MINISTRY_ID` )
    REFERENCES `rise`.`MINISTRY` (`MINISTRY_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MINISTRY_has_DEPARTMENT_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT_ID` )
    REFERENCES `rise`.`DEPARTMENT` (`DEPARTMENT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MINISTRY_has_DEPARTMENT_DEPARTMENT1_idx` ON `rise`.`MINISTRY_DEPARTMENT` (`DEPARTMENT_ID` ASC) ;

CREATE INDEX `fk_MINISTRY_has_DEPARTMENT_MINISTRY1_idx` ON `rise`.`MINISTRY_DEPARTMENT` (`MINISTRY_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`TRAINING_PROVIDER_EMPANELMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`TRAINING_PROVIDER_EMPANELMENT` ;

CREATE  TABLE IF NOT EXISTS `rise`.`TRAINING_PROVIDER_EMPANELMENT` (
  `TRAINING_PROVIDER_EMPANELMENT_ID` BIGINT NOT NULL ,
  `DATE_REQUESTED` DATETIME NOT NULL ,
  `DATE_APPROVED` DATETIME NOT NULL ,
  `FROM_DATE` DATETIME NOT NULL ,
  `TO_DATE` DATETIME NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`TRAINING_PROVIDER_EMPANELMENT_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rise`.`EMPLOYMENT_AGENCY_EMPANELMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`EMPLOYMENT_AGENCY_EMPANELMENT` ;

CREATE  TABLE IF NOT EXISTS `rise`.`EMPLOYMENT_AGENCY_EMPANELMENT` (
  `EMPLOYMENT_AGENCY_EMPANELMENT_ID` BIGINT NOT NULL ,
  `DATE_REQUESTED` DATETIME NOT NULL ,
  `DATE_APPROVED` DATETIME NOT NULL ,
  `FROM_DATE` DATETIME NOT NULL ,
  `TO_DATE` DATETIME NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`EMPLOYMENT_AGENCY_EMPANELMENT_ID`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rise`.`PROGRAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`PROGRAM` ;

CREATE  TABLE IF NOT EXISTS `rise`.`PROGRAM` (
  `PROGRAM_ID` BIGINT NOT NULL ,
  `CONTACT_INFORMATION_ID` BIGINT NOT NULL ,
  `TRAINING_PROVIDER_EMPANELMENT_ID` BIGINT NOT NULL ,
  `EMPLOYMENT_AGENCY_EMPANELMENT_ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `INCHARGE_OFFICER` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`PROGRAM_ID`) ,
  CONSTRAINT `fk_PROGRAM_TRAINING_PROVIDER_EMPANELMENT1`
    FOREIGN KEY (`TRAINING_PROVIDER_EMPANELMENT_ID` )
    REFERENCES `rise`.`TRAINING_PROVIDER_EMPANELMENT` (`TRAINING_PROVIDER_EMPANELMENT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROGRAM_EMPLOYMENT_AGENCY_EMPANELMENT1`
    FOREIGN KEY (`EMPLOYMENT_AGENCY_EMPANELMENT_ID` )
    REFERENCES `rise`.`EMPLOYMENT_AGENCY_EMPANELMENT` (`EMPLOYMENT_AGENCY_EMPANELMENT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROGRAM_ADDRESS1`
    FOREIGN KEY (`CONTACT_INFORMATION_ID` )
    REFERENCES `rise`.`CONTACT_INFORMATION` (`CONTACT_INFORMATION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PROGRAM_TRAINING_PROVIDER_EMPANELMENT1_idx` ON `rise`.`PROGRAM` (`TRAINING_PROVIDER_EMPANELMENT_ID` ASC) ;

CREATE INDEX `fk_PROGRAM_EMPLOYMENT_AGENCY_EMPANELMENT1_idx` ON `rise`.`PROGRAM` (`EMPLOYMENT_AGENCY_EMPANELMENT_ID` ASC) ;

CREATE INDEX `fk_PROGRAM_ADDRESS1_idx` ON `rise`.`PROGRAM` (`CONTACT_INFORMATION_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`DEPARTMENT_PROGRAM`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`DEPARTMENT_PROGRAM` ;

CREATE  TABLE IF NOT EXISTS `rise`.`DEPARTMENT_PROGRAM` (
  `DEPARTMENT_PROGRAM_ID` BIGINT NOT NULL ,
  `DEPARTMENT_ID` BIGINT NOT NULL ,
  `PROGRAM_ID` BIGINT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`DEPARTMENT_PROGRAM_ID`) ,
  CONSTRAINT `fk_DEPARTMENT_has_PROGRAM_DEPARTMENT1`
    FOREIGN KEY (`DEPARTMENT_ID` )
    REFERENCES `rise`.`DEPARTMENT` (`DEPARTMENT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DEPARTMENT_has_PROGRAM_PROGRAM1`
    FOREIGN KEY (`PROGRAM_ID` )
    REFERENCES `rise`.`PROGRAM` (`PROGRAM_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_DEPARTMENT_has_PROGRAM_PROGRAM1_idx` ON `rise`.`DEPARTMENT_PROGRAM` (`PROGRAM_ID` ASC) ;

CREATE INDEX `fk_DEPARTMENT_has_PROGRAM_DEPARTMENT1_idx` ON `rise`.`DEPARTMENT_PROGRAM` (`DEPARTMENT_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`TRAINING_PROVIDER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`TRAINING_PROVIDER` ;

CREATE  TABLE IF NOT EXISTS `rise`.`TRAINING_PROVIDER` (
  `TRAINING_PROVIDER_ID` BIGINT NOT NULL ,
  `CONTACT_INFORMATION_ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `CONTACT_PERSON_NAME` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`TRAINING_PROVIDER_ID`) ,
  CONSTRAINT `fk_TRAINING_PROVIDER_ADDRESS1`
    FOREIGN KEY (`CONTACT_INFORMATION_ID` )
    REFERENCES `rise`.`CONTACT_INFORMATION` (`CONTACT_INFORMATION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TRAINING_PROVIDER_ADDRESS1_idx` ON `rise`.`TRAINING_PROVIDER` (`CONTACT_INFORMATION_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`EMPLOYMENT_AGENCY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`EMPLOYMENT_AGENCY` ;

CREATE  TABLE IF NOT EXISTS `rise`.`EMPLOYMENT_AGENCY` (
  `EMPLOYMENT_AGENCY_ID` BIGINT NOT NULL ,
  `CONTACT_INFORMATION_ID` BIGINT NOT NULL ,
  `NAME` VARCHAR(255) NOT NULL ,
  `CONTACT_PERSON_NAME` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`EMPLOYMENT_AGENCY_ID`) ,
  CONSTRAINT `fk_EMPLOYMENT_AGENCY_ADDRESS1`
    FOREIGN KEY (`CONTACT_INFORMATION_ID` )
    REFERENCES `rise`.`CONTACT_INFORMATION` (`CONTACT_INFORMATION_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EMPLOYMENT_AGENCY_ADDRESS1_idx` ON `rise`.`EMPLOYMENT_AGENCY` (`CONTACT_INFORMATION_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`JOB_POSTING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`JOB_POSTING` ;

CREATE  TABLE IF NOT EXISTS `rise`.`JOB_POSTING` (
  `JOB_POSTING_ID` BIGINT NOT NULL ,
  `EMPLOYMENT_AGENCY_ID` BIGINT NOT NULL ,
  `JOB_HEADING` VARCHAR(255) NOT NULL ,
  `JOB_TITLE` VARCHAR(255) NOT NULL ,
  `JOB_CITY` VARCHAR(255) NOT NULL ,
  `JOB_STATE` VARCHAR(255) NOT NULL ,
  `DATE_POSTED` DATE NOT NULL ,
  `DATE_LAST_UPDATED` DATETIME NOT NULL ,
  `JOB_DESCRIPTION` TEXT NOT NULL ,
  `EMPLOYMENT_AGENCY_NAME` VARCHAR(255) NOT NULL ,
  `JOB_POSTER_NAME` VARCHAR(255) NOT NULL ,
  `JOB_POSTER_EMAIL_ADDRESS` VARCHAR(255) NOT NULL ,
  `JOB_POSTER_MOBILE_NUMBER` VARCHAR(255) NOT NULL ,
  `VERIFIED` TINYINT(1) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`JOB_POSTING_ID`) ,
  CONSTRAINT `fk_JOB_POSTING_EMPLOYMENT_AGENCY1`
    FOREIGN KEY (`EMPLOYMENT_AGENCY_ID` )
    REFERENCES `rise`.`EMPLOYMENT_AGENCY` (`EMPLOYMENT_AGENCY_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_JOB_POSTING_EMPLOYMENT_AGENCY1_idx` ON `rise`.`JOB_POSTING` (`EMPLOYMENT_AGENCY_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`CANDIDATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`CANDIDATE` ;

CREATE  TABLE IF NOT EXISTS `rise`.`CANDIDATE` (
  `CANDIDATE_ID` BIGINT NOT NULL ,
  `PERSON_ID` BIGINT NOT NULL ,
  `CONTACT_PERSON_NAME` VARCHAR(255) NOT NULL ,
  `PRESENT_ADDRESS` VARCHAR(255) NOT NULL ,
  `PRESENT_CITY` VARCHAR(255) NOT NULL ,
  `PRESENT_STATE` VARCHAR(255) NOT NULL ,
  `PRESENT_POSTAL_CODE` VARCHAR(255) NOT NULL ,
  `PRESENT_COUNTRY` VARCHAR(255) NOT NULL ,
  `PERMANENT_ADDRESS` VARCHAR(255) NOT NULL ,
  `PERMANENT_CITY` VARCHAR(255) NOT NULL ,
  `PERMANENT_STATE` VARCHAR(255) NOT NULL ,
  `PERMANENT_POSTAL_CODE` VARCHAR(255) NOT NULL ,
  `PERMANENT_COUNTRY` VARCHAR(255) NOT NULL ,
  `EMAIL` VARCHAR(255) NOT NULL ,
  `ALTERNATIVE_EMAIL` VARCHAR(255) NOT NULL ,
  `PHONE` VARCHAR(255) NOT NULL ,
  `ALTERNATIVE_PHONE` VARCHAR(255) NOT NULL ,
  `WEBSITE` VARCHAR(255) NOT NULL ,
  `PF_NUMBER` VARCHAR(255) NOT NULL ,
  `ESI_NUMBER` VARCHAR(255) NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`CANDIDATE_ID`) ,
  CONSTRAINT `fk_CANDIDATE_PERSON1`
    FOREIGN KEY (`PERSON_ID` )
    REFERENCES `rise`.`PERSON` (`PERSON_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CANDIDATE_PERSON1_idx` ON `rise`.`CANDIDATE` (`PERSON_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`CANDIDATE_JOB_POSTING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`CANDIDATE_JOB_POSTING` ;

CREATE  TABLE IF NOT EXISTS `rise`.`CANDIDATE_JOB_POSTING` (
  `CANDIDATE_JOB_POSTING_ID` BIGINT NOT NULL ,
  `CANDIDATE_CANDIDATE_ID` BIGINT NOT NULL ,
  `JOB_POSTING_JOB_POSTING_ID` BIGINT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`CANDIDATE_JOB_POSTING_ID`) ,
  CONSTRAINT `fk_CANDIDATE_has_JOB_POSTING_CANDIDATE1`
    FOREIGN KEY (`CANDIDATE_CANDIDATE_ID` )
    REFERENCES `rise`.`CANDIDATE` (`CANDIDATE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CANDIDATE_has_JOB_POSTING_JOB_POSTING1`
    FOREIGN KEY (`JOB_POSTING_JOB_POSTING_ID` )
    REFERENCES `rise`.`JOB_POSTING` (`JOB_POSTING_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CANDIDATE_has_JOB_POSTING_JOB_POSTING1_idx` ON `rise`.`CANDIDATE_JOB_POSTING` (`JOB_POSTING_JOB_POSTING_ID` ASC) ;

CREATE INDEX `fk_CANDIDATE_has_JOB_POSTING_CANDIDATE1_idx` ON `rise`.`CANDIDATE_JOB_POSTING` (`CANDIDATE_CANDIDATE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`STATE_MINISTRY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`STATE_MINISTRY` ;

CREATE  TABLE IF NOT EXISTS `rise`.`STATE_MINISTRY` (
  `STATE_MINISTRY_ID` BIGINT NOT NULL ,
  `STATE_ID` BIGINT NOT NULL ,
  `MINISTRY_ID` BIGINT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`STATE_MINISTRY_ID`) ,
  CONSTRAINT `fk_STATE_has_MINISTRY_STATE1`
    FOREIGN KEY (`STATE_ID` )
    REFERENCES `rise`.`STATE` (`STATE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_STATE_has_MINISTRY_MINISTRY1`
    FOREIGN KEY (`MINISTRY_ID` )
    REFERENCES `rise`.`MINISTRY` (`MINISTRY_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_STATE_has_MINISTRY_MINISTRY1_idx` ON `rise`.`STATE_MINISTRY` (`MINISTRY_ID` ASC) ;

CREATE INDEX `fk_STATE_has_MINISTRY_STATE1_idx` ON `rise`.`STATE_MINISTRY` (`STATE_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`TRAINING_PROVIDER_TRAINING_PROVIDER_EMPANELMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`TRAINING_PROVIDER_TRAINING_PROVIDER_EMPANELMENT` ;

CREATE  TABLE IF NOT EXISTS `rise`.`TRAINING_PROVIDER_TRAINING_PROVIDER_EMPANELMENT` (
  `TRAINING_PROVIDER_TRAINING_PROVIDER_EMPANELMENT_ID` BIGINT NOT NULL ,
  `TRAINING_PROVIDER_ID` BIGINT NOT NULL ,
  `TRAINING_PROVIDER_EMPANELMENT_ID` BIGINT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`TRAINING_PROVIDER_TRAINING_PROVIDER_EMPANELMENT_ID`) ,
  CONSTRAINT `fk_TRAINING_PROVIDER_has_TRAINING_PROVIDER_EMPANELMENT_TRAINI1`
    FOREIGN KEY (`TRAINING_PROVIDER_ID` )
    REFERENCES `rise`.`TRAINING_PROVIDER` (`TRAINING_PROVIDER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRAINING_PROVIDER_has_TRAINING_PROVIDER_EMPANELMENT_TRAINI2`
    FOREIGN KEY (`TRAINING_PROVIDER_EMPANELMENT_ID` )
    REFERENCES `rise`.`TRAINING_PROVIDER_EMPANELMENT` (`TRAINING_PROVIDER_EMPANELMENT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TRAINING_PROVIDER_has_TRAINING_PROVIDER_EMPANELMENT_TRAI_idx` ON `rise`.`TRAINING_PROVIDER_TRAINING_PROVIDER_EMPANELMENT` (`TRAINING_PROVIDER_EMPANELMENT_ID` ASC) ;

CREATE INDEX `fk_TRAINING_PROVIDER_has_TRAINING_PROVIDER_EMPANELMENT_TRAI_idx1` ON `rise`.`TRAINING_PROVIDER_TRAINING_PROVIDER_EMPANELMENT` (`TRAINING_PROVIDER_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`EMPLOYMENT_AGENCY_EMPLOYMENT_AGENCY_EMPANELMENT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`EMPLOYMENT_AGENCY_EMPLOYMENT_AGENCY_EMPANELMENT` ;

CREATE  TABLE IF NOT EXISTS `rise`.`EMPLOYMENT_AGENCY_EMPLOYMENT_AGENCY_EMPANELMENT` (
  `EMPLOYMENT_AGENCY_EMPLOYMENT_AGENCY_EMPANELMENT_ID` BIGINT NOT NULL ,
  `EMPLOYMENT_AGENCY_ID` BIGINT NOT NULL ,
  `EMPLOYMENT_AGENCY_EMPANELMENT_ID` BIGINT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`EMPLOYMENT_AGENCY_EMPLOYMENT_AGENCY_EMPANELMENT_ID`) ,
  CONSTRAINT `fk_EMPLOYMENT_AGENCY_has_EMPLOYMENT_AGENCY_EMPANELMENT_EMPLOY1`
    FOREIGN KEY (`EMPLOYMENT_AGENCY_ID` )
    REFERENCES `rise`.`EMPLOYMENT_AGENCY` (`EMPLOYMENT_AGENCY_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPLOYMENT_AGENCY_has_EMPLOYMENT_AGENCY_EMPANELMENT_EMPLOY2`
    FOREIGN KEY (`EMPLOYMENT_AGENCY_EMPANELMENT_ID` )
    REFERENCES `rise`.`EMPLOYMENT_AGENCY_EMPANELMENT` (`EMPLOYMENT_AGENCY_EMPANELMENT_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_EMPLOYMENT_AGENCY_has_EMPLOYMENT_AGENCY_EMPANELMENT_EMPL_idx` ON `rise`.`EMPLOYMENT_AGENCY_EMPLOYMENT_AGENCY_EMPANELMENT` (`EMPLOYMENT_AGENCY_EMPANELMENT_ID` ASC) ;

CREATE INDEX `fk_EMPLOYMENT_AGENCY_has_EMPLOYMENT_AGENCY_EMPANELMENT_EMPL_idx1` ON `rise`.`EMPLOYMENT_AGENCY_EMPLOYMENT_AGENCY_EMPANELMENT` (`EMPLOYMENT_AGENCY_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`TRAINING_PROVIDER_JOB_POSTING`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`TRAINING_PROVIDER_JOB_POSTING` ;

CREATE  TABLE IF NOT EXISTS `rise`.`TRAINING_PROVIDER_JOB_POSTING` (
  `TRAINING_PROVIDER_JOB_POSTING_ID` BIGINT NOT NULL ,
  `TRAINING_PROVIDER_ID` BIGINT NOT NULL ,
  `JOB_POSTING_ID` BIGINT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`TRAINING_PROVIDER_JOB_POSTING_ID`) ,
  CONSTRAINT `fk_TRAINING_PROVIDER_has_JOB_POSTING_TRAINING_PROVIDER1`
    FOREIGN KEY (`TRAINING_PROVIDER_ID` )
    REFERENCES `rise`.`TRAINING_PROVIDER` (`TRAINING_PROVIDER_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TRAINING_PROVIDER_has_JOB_POSTING_JOB_POSTING1`
    FOREIGN KEY (`JOB_POSTING_ID` )
    REFERENCES `rise`.`JOB_POSTING` (`JOB_POSTING_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TRAINING_PROVIDER_has_JOB_POSTING_JOB_POSTING1_idx` ON `rise`.`TRAINING_PROVIDER_JOB_POSTING` (`JOB_POSTING_ID` ASC) ;

CREATE INDEX `fk_TRAINING_PROVIDER_has_JOB_POSTING_TRAINING_PROVIDER1_idx` ON `rise`.`TRAINING_PROVIDER_JOB_POSTING` (`TRAINING_PROVIDER_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`PERSON_AWARD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`PERSON_AWARD` ;

CREATE  TABLE IF NOT EXISTS `rise`.`PERSON_AWARD` (
  `PERSON_AWARD_ID` BIGINT NOT NULL ,
  `PERSON_ID` BIGINT NOT NULL ,
  `AWARD_ID` BIGINT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`PERSON_AWARD_ID`) ,
  CONSTRAINT `fk_PERSON_has_AWARD_PERSON1`
    FOREIGN KEY (`PERSON_ID` )
    REFERENCES `rise`.`PERSON` (`PERSON_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSON_has_AWARD_AWARD1`
    FOREIGN KEY (`AWARD_ID` )
    REFERENCES `rise`.`AWARD` (`AWARD_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PERSON_has_AWARD_AWARD1_idx` ON `rise`.`PERSON_AWARD` (`AWARD_ID` ASC) ;

CREATE INDEX `fk_PERSON_has_AWARD_PERSON1_idx` ON `rise`.`PERSON_AWARD` (`PERSON_ID` ASC) ;


-- -----------------------------------------------------
-- Table `rise`.`PERSON_EMPLOYMENT_EXPERIENCE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rise`.`PERSON_EMPLOYMENT_EXPERIENCE` ;

CREATE  TABLE IF NOT EXISTS `rise`.`PERSON_EMPLOYMENT_EXPERIENCE` (
  `PERSON_EMPLOYMENT_EXPERIENCE_ID` BIGINT NOT NULL ,
  `PERSON_ID` BIGINT NOT NULL ,
  `EMPLOYMENT_EXPERIENCE_ID` BIGINT NOT NULL ,
  `CREATED_BY` BIGINT NOT NULL ,
  `DATE_CREATED` DATETIME NOT NULL ,
  `MODIFIED_BY` BIGINT NOT NULL ,
  `DATE_MODIFIED` DATETIME NOT NULL ,
  `RECORD_STATUS` CHAR(1) NOT NULL ,
  PRIMARY KEY (`PERSON_EMPLOYMENT_EXPERIENCE_ID`) ,
  CONSTRAINT `fk_PERSON_has_EMPLOYMENT_EXPERIENCE_PERSON1`
    FOREIGN KEY (`PERSON_ID` )
    REFERENCES `rise`.`PERSON` (`PERSON_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PERSON_has_EMPLOYMENT_EXPERIENCE_EMPLOYMENT_EXPERIENCE1`
    FOREIGN KEY (`EMPLOYMENT_EXPERIENCE_ID` )
    REFERENCES `rise`.`EMPLOYMENT_EXPERIENCE` (`EMPLOYMENT_EXPERIENCE_ID` )
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PERSON_has_EMPLOYMENT_EXPERIENCE_EMPLOYMENT_EXPERIENCE1_idx` ON `rise`.`PERSON_EMPLOYMENT_EXPERIENCE` (`EMPLOYMENT_EXPERIENCE_ID` ASC) ;

CREATE INDEX `fk_PERSON_has_EMPLOYMENT_EXPERIENCE_PERSON1_idx` ON `rise`.`PERSON_EMPLOYMENT_EXPERIENCE` (`PERSON_ID` ASC) ;

USE `rise` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
