//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.13 at 01:31:48 PM IST 
//


package com.rise.xmlns.common.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rise.xmlns.common.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QueryConfigs_QNAME = new QName("http://xmlns.rise.com/common/v1", "queryConfigs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rise.xmlns.common.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QueryConfigs }
     * 
     */
    public QueryConfigs createQueryConfigs() {
        return new QueryConfigs();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link Component }
     * 
     */
    public Component createComponent() {
        return new Component();
    }

    /**
     * Create an instance of {@link QueryConfig }
     * 
     */
    public QueryConfig createQueryConfig() {
        return new QueryConfig();
    }

    /**
     * Create an instance of {@link SuperClass }
     * 
     */
    public SuperClass createSuperClass() {
        return new SuperClass();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryConfigs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.rise.com/common/v1", name = "queryConfigs")
    public JAXBElement<QueryConfigs> createQueryConfigs(QueryConfigs value) {
        return new JAXBElement<QueryConfigs>(_QueryConfigs_QNAME, QueryConfigs.class, null, value);
    }

}
