//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.07 at 05:13:35 PM IST 
//


package com.generator.data.xmlns.configuration.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.generator.data.xmlns.configuration.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataSourceConfiguration_QNAME = new QName("http://xmlns.data.generator.com/configuration/v1", "dataSourceConfiguration");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.generator.data.xmlns.configuration.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataSourceConfiguration }
     * 
     */
    public DataSourceConfiguration createDataSourceConfiguration() {
        return new DataSourceConfiguration();
    }

    /**
     * Create an instance of {@link DataSource }
     * 
     */
    public DataSource createDataSource() {
        return new DataSource();
    }

    /**
     * Create an instance of {@link Field }
     * 
     */
    public Field createField() {
        return new Field();
    }

    /**
     * Create an instance of {@link PicklistItem }
     * 
     */
    public PicklistItem createPicklistItem() {
        return new PicklistItem();
    }

    /**
     * Create an instance of {@link AdditionalDataSource }
     * 
     */
    public AdditionalDataSource createAdditionalDataSource() {
        return new AdditionalDataSource();
    }

    /**
     * Create an instance of {@link DataSourceFieldName }
     * 
     */
    public DataSourceFieldName createDataSourceFieldName() {
        return new DataSourceFieldName();
    }

    /**
     * Create an instance of {@link ObjectRef }
     * 
     */
    public ObjectRef createObjectRef() {
        return new ObjectRef();
    }

    /**
     * Create an instance of {@link BaseObject }
     * 
     */
    public BaseObject createBaseObject() {
        return new BaseObject();
    }

    /**
     * Create an instance of {@link Entity }
     * 
     */
    public Entity createEntity() {
        return new Entity();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSourceConfiguration }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.data.generator.com/configuration/v1", name = "dataSourceConfiguration")
    public JAXBElement<DataSourceConfiguration> createDataSourceConfiguration(DataSourceConfiguration value) {
        return new JAXBElement<DataSourceConfiguration>(_DataSourceConfiguration_QNAME, DataSourceConfiguration.class, null, value);
    }

}
