//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.29 at 03:36:24 PM IST 
//


package com.generator.data.xmlns.geo.names.api.v1;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GeoNames complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GeoNames">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="totalResultsCount" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="geoname" type="{http://xmlns.data.generator.com/geo/names/api/v1}GeoName" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="status" type="{http://xmlns.data.generator.com/geo/names/api/v1}Status"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GeoNames", propOrder = {
    "totalResultsCount",
    "geoname",
    "status"
})
public class GeoNames {

    protected int totalResultsCount;
    protected List<GeoName> geoname;
    @XmlElement(required = true)
    protected Status status;

    /**
     * Gets the value of the totalResultsCount property.
     * 
     */
    public int getTotalResultsCount() {
        return totalResultsCount;
    }

    /**
     * Sets the value of the totalResultsCount property.
     * 
     */
    public void setTotalResultsCount(int value) {
        this.totalResultsCount = value;
    }

    /**
     * Gets the value of the geoname property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geoname property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeoname().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeoName }
     * 
     * 
     */
    public List<GeoName> getGeoname() {
        if (geoname == null) {
            geoname = new ArrayList<GeoName>();
        }
        return this.geoname;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

}
