//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.30 at 11:01:09 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.data.generator.com/geo/names/api/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.generator.data.xmlns.geo.names.api.v1;
