//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.29 at 03:36:24 PM IST 
//


package com.generator.data.xmlns.geo.names.api.v1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.generator.data.xmlns.geo.names.api.v1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Geonames_QNAME = new QName("http://xmlns.data.generator.com/geo/names/api/v1", "geonames");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.generator.data.xmlns.geo.names.api.v1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeoNames }
     * 
     */
    public GeoNames createGeoNames() {
        return new GeoNames();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link GeoName }
     * 
     */
    public GeoName createGeoName() {
        return new GeoName();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeoNames }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://xmlns.data.generator.com/geo/names/api/v1", name = "geonames")
    public JAXBElement<GeoNames> createGeonames(GeoNames value) {
        return new JAXBElement<GeoNames>(_Geonames_QNAME, GeoNames.class, null, value);
    }

}
